#ifndef GPSDataTypes_idl
#define GPSDataTypes_idl

#include "InterfaceDataTypes.idl"

module GPSData{

    /*!
     * @struct TimedGPSData
     * @brief GPS data include time and accuracy
     */
    struct TimedGPSData
    {
        /// Time stamp.
        RTC::Time tm;
        /// Longitude from GPS
        double longitude;
        /// Latitude from GPS
        double latitude;
        /// Variance of GPS Data
        double variance;
        /// Number of satellites
        int satellites;
    };

};

#endif